// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhdAf49wTIqcSTTG9YtXM7TVcFZl7uc08',
    appId: '1:634448351189:web:555b8f284a0e3ae7dd775c',
    messagingSenderId: '634448351189',
    projectId: 'holysht',
    authDomain: 'holysht.firebaseapp.com',
    storageBucket: 'holysht.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuRlHsPM2P5YsNf2wPZ4zx2Xrr5nHLuE',
    appId: '1:634448351189:android:aec447031955c456dd775c',
    messagingSenderId: '634448351189',
    projectId: 'holysht',
    storageBucket: 'holysht.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCroHaaUfZEyyjXvXnYIrV6sbLK0WvhhwY',
    appId: '1:634448351189:ios:ddef93c739ecf776dd775c',
    messagingSenderId: '634448351189',
    projectId: 'holysht',
    storageBucket: 'holysht.firebasestorage.app',
    iosBundleId: 'com.tradeforge.tradeforgeV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhdAf49wTIqcSTTG9YtXM7TVcFZl7uc08',
    appId: '1:634448351189:web:62733846da01f4fbdd775c',
    messagingSenderId: '634448351189',
    projectId: 'holysht',
    authDomain: 'holysht.firebaseapp.com',
    storageBucket: 'holysht.firebasestorage.app',
  );
}
